kind: Secret
apiVersion: v1
metadata:
  name: quarkus-app-credentials
  namespace: YOUR_NAMESPACE
type: Opaque
stringData:
  database-name: "tp-demo"
  database-password: "MyPassw0rd"
  database-user: "tp-demo"
  database-host: "sql.secdavid.com"